In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'splitter':['best','random'],'max_features':['sqrt','log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [13]:
re=grid.cv_results_
print(" best parameter {}:".format(grid.best_params_))

 best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018745,6.248856e-03,0.003124,0.006249,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.702316,0.597881,0.659254,0.633222,0.719301,0.662395,0.044396,11
1,0.009373,1.249683e-02,0.009372,0.007652,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.699928,0.543750,0.701164,0.721388,0.628430,0.658932,0.065669,12
2,0.015622,9.879931e-03,0.006248,0.007653,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.647144,0.627566,0.719263,0.450757,0.679779,0.624902,0.092460,16
3,0.006248,7.652436e-03,0.006248,0.007652,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.701555,0.563338,0.690060,0.756024,0.686188,0.679433,0.063233,8
4,0.012496,6.248188e-03,0.006249,0.007653,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.732979,0.623106,0.671536,0.728808,0.717712,0.694828,0.042001,3
5,0.012497,6.248569e-03,0.003124,0.006249,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.673868,0.542418,0.693355,0.685027,0.631222,0.645178,0.055654,15
6,0.012497,1.169008e-02,0.006249,0.007653,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.694382,0.590723,0.748464,0.678278,0.709822,0.684334,0.052274,6
7,0.015621,4.768372e-07,0.000000,0.000000,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.714228,0.594438,0.674224,0.702317,0.744199,0.685881,0.050936,5
8,0.046863,0.000000e+00,0.006249,0.007653,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.765115,0.640463,0.733423,0.756196,0.692413,0.717522,0.046005,1
9,0.031243,9.880157e-03,0.003124,0.006248,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.638447,0.566580,0.759221,0.695913,0.660305,0.664093,0.063628,10
10,0.034367,6.249047e-03,0.003124,0.006248,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.642703,0.617134,0.644780,0.696418,0.666372,0.653482,0.026544,13
11,0.028118,6.248999e-03,0.006249,0.007653,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.795614,0.541110,0.628261,0.741028,0.650238,0.671250,0.088951,9
12,0.015621,3.873843e-07,0.006248,0.007653,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.690543,0.631783,0.764702,0.736321,0.721126,0.708895,0.045386,2
13,0.012497,6.248737e-03,0.003124,0.006248,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.637687,0.503640,0.690116,0.666267,0.729176,0.645377,0.076953,14
14,0.015621,9.879931e-03,0.009372,0.007652,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.629895,0.673143,0.754553,0.673322,0.742198,0.694622,0.046818,4
15,0.006249,7.652845e-03,0.003125,0.006249,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.760769,0.572286,0.660252,0.698068,0.725151,0.683305,0.064539,7